---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-whale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: nginx-web
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: web-app
        image: sakthinatural123/testing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service 
metadata:
  name: nginx-web-svc
  labels:
    app: nginx-web
    env: dev
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: nginx-web
  ports:
    - nodePort: 31008
      port: 80
      targetPort: 80
