apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web-app
    env: dev
  namespace: jenkins
spec:
  containers:
  - name: web-app
    image: sakthinatural123/testing:latest
    ports:
    - containerPort: 80
      protocol: TCP  
---

apiVersion: v1
kind: Service 
metadata:
  name: web-web
  labels:
    app: web-web
    env: dev
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31008
    targetPort: 80
