---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-app
        image: sakthinatural123/testing:latest
        ports:
        - containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Service 
metadata:
  name: web-web
  labels:
    app: web-web
    env: dev
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31008
    targetPort: 80
