apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
    env: dev
  namespace: test
spec:
  containers:
  - name: nginx-app
    image: sakthinatural123/testing:latest
    ports:
    - containerPort: 80
      protocol: TCP  
---

apiVersion: v1
kind: Service 
metadata:
  name: nginx-web
  labels:
    app: nginx-web
    env: dev
  namespace: test
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31008
    targetPort: 80
